function [ result ] = Distance( A,B )
%UNTITLED5 Summary of this function goes here
%   Detailed explanation goes here
width = 2;
element = strel('square',width);
w1 = 0.6;
w2 = 0.2;
w3 = 0.2;

% result = w1*Dis_C(A,B,80) ...
%        + w2*Dis_C(imopen(A,element), ...
%                 imopen(B,element),80) ...
%        + w3*Dis_C(imclose(A,element),...
%                 imclose(B,element),80); 

result = w1*Dis(A,B,80) ...
       + w2*Dis(imopen(A,element), ...
                imopen(B,element),80) ...
       + w3*Dis(imclose(A,element),...
                imclose(B,element),80); 
end

